version: '3'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - mssp
    volumes:
      - ./redis-data:/data


  redis_ui:
    image: redislabs/redisinsight
    container_name: redis_ui
    ports:
      - 8001:8001
    networks:
      - mssp
    volumes:
      - ./redis-ui-data:/db
      
   
    
networks:
  mssp:
    external: true